# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-26 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpLoadToraText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.FileField(blank=True, null=True, upload_to='')),
                ('comment', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Yeshiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rav_name', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='uploadtoratext',
            name='yeshiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeshiva', to='ToraSearch.Yeshiva'),
        ),
    ]
